import { OpenAIClient, AzureKeyCredential } from "@azure/openai"

export default defineEventHandler(async (event) => {
    if (!event.context.user) {
        throw createError({
            message: "Unauthorised",
            statusCode: 401
        });
    }

    const body = await readBody(event)
    const prompt = body.prompt
    const config = useRuntimeConfig()
    const azureOpenAiApiKey = config.azureOpenAiApiKey
    const endpoint = "https://codeface.openai.azure.com/"
	const client = new OpenAIClient(endpoint, new AzureKeyCredential(azureOpenAiApiKey));
    const deploymentId = "llm";
    const chatHistory = [
        { role: "system", content: `You are an agent who turns user prompts into original responsive tailwindcss code using html.
        Given the prompt generate the code and do not have anything in front or back of it not even backticks. just the code is needed. Make it beautiful. Also for src properties, dont use any company or logo made up urls unless specified. Just use # instead. For links do not at any cost include href attribute. If previous generated code generated by you only is present, modify the existing code only according to changes specified in the prompt and rewrite the whole code.` },
    ]
    if(body.history==-1) {
        chatHistory.push( { role: "user", content: `Prompt: ${prompt}` })
    }
    else {
        body.history.forEach((x)=>{
            chatHistory.push({
                role: "user",
                content: x.prompt
            })
            if(x.html!='') {
                chatHistory.push({
                    role: "assistant",
                    content: x.html
                })
            }
        })
    }
    console.log(chatHistory)
    const result = await client.getChatCompletions(deploymentId, chatHistory
    , { maxTokens: 4096 });

    let fullResponse = ""
    for (const choice of result.choices) {
      fullResponse += choice.message.content
    }
  
    console.log(fullResponse)
    return fullResponse

})